### ISSUE TITLE
Fix CRM styling issues

### ISSUE THREAD

**Issue by DigitalFlow** [DigitalFlow/D365-PowerKanban#18]
Embedding of bootstrap in the whole page causes some style issues in navbar and bpf controls.
Caused by bootstrap.css:
```css
dl, ol, ul {
       margin-top: 0;
    /* margin-bottom: 1rem; */
}
```

```css
label {
    display: inline-block;
    /* margin-bottom: .5rem; */
}
```

Uncommented css options above are those which cause styling issues.
